apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-app
  namespace: iot
spec:
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
      - name: consumer-app
        image: sharhanalhassan/iotconsumer:0.0.12
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: general-config
        - secretRef:
            name: smtp-secrets
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: consumer-app
  namespace: iot
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: consumer-app
  type: ClusterIP
---
