#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "consumer-service.fullname" . }}
#  namespace: {{ .Values.service.namespace }}
#  labels:
#    {{- include "consumer-service.labels" . | nindent 4 }}
#spec:
#  type: {{ .Values.service.type }}
#  ports:
#    - port: {{ .Values.service.port }}
#      targetPort: http
#      protocol: TCP
#      name: http
#  selector:
#    {{- include "consumer-service.selectorLabels" . | nindent 4 }}
kind: Service
apiVersion: v1
metadata:
  name: consumer-app
  namespace: iot
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: consumer-app
  type: ClusterIP
