apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: iot
spec:
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: sharhanalhassan/iotapp:0.0.14
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: general-config
        - secretRef:
            name: smtp-secrets
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: api-service
  namespace: iot
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: api-service
  type: ClusterIP
---
